server:
  port: 6515

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  file:
    name: logs/server.temp.log
  logback:
    rollingpolicy:
      max-history: 14
      max-file-size: 2MB
      file-name-pattern: logs/server.%d{yyyy-MM-dd}.%i.log
