spring:
  data:
    redis:
      host: 192.168.88.139
      password: 123321

server:
  port: 6515

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  file:
    name: temp.log
  logback:
    rollingpolicy:
      max-history: 14
      max-file-size: 2MB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log

