spring:
  profiles:
    active: dev

server:
  port: 1165

logging:
  file:
    name: temp.log
  logback:
    rollingpolicy:
      max-history: 7
      max-file-size: 256KB
      file-name-pattern: server.%d{yyyy-MM-dd}.%i.log
